eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

cat <<EOF
Welcome to Jepsen on Docker
===========================

This container runs the Jepsen tests in sub-containers.

You are currently in the base dir of the git repo for the fuzz_dist framework for Jepsen.

To run a test:

   lein run test
EOF

cd /var/jepsen/shared/jepsen.fuzz_dist
